"""SHIPP — small, auditable Streamlit entry point.

Generated by local refactor of the CURRENT application. Existing business
workflows live in ui/pages and keep using the existing Agent/Lakebase modules.
"""
from __future__ import annotations

import streamlit as st

st.set_page_config(
    page_title="SHIPP Marketplace",
    page_icon="📦",
    layout="wide",
    initial_sidebar_state="collapsed",
)

from ui import legacy_core as core  # noqa: E402  (configure Streamlit first)
from ui.components.navbar import create_navigation  # noqa: E402

core.initialize_session()
core.load_css()

navigation = create_navigation()
navigation.run()
